trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Agent.BuildDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
